export const uploadSettings = {
  'uploadSettings.screenshotsTitle': 'Screenshots',
  'uploadSettings.screenshotsDescription': 'Applied to the next upload prepared, not retroactive on ones already ready.',
  'uploadSettings.screenshotCountLabel': 'Screenshot count',
  'uploadSettings.screenshotCountDescription': 'Equally spaced frames, excludes the first/last 5% of the duration.',
  'uploadSettings.tonemapLabel': 'Tonemap HDR in screenshots',
  'uploadSettings.tonemapDescription':
    'Converts HDR→SDR (mobius algorithm) before capturing screenshots — without it, an HDR source looks washed out/dark once interpreted as SDR.',
  'uploadSettings.descriptionTitle': 'Description',
  'uploadSettings.descriptionHeaderLabel': 'Description header',
  'uploadSettings.descriptionHeaderHelp':
    'Text (e.g. BBCode) prepended to the description generated by the tracker template — leave empty to add nothing.',
  'uploadSettings.descriptionHeaderSaved': 'Header saved.',
  'uploadSettings.saveHeaderButton': 'Save header',
  'uploadSettings.signatureLabel': 'Signature',
  'uploadSettings.signatureHelp':
    'Text (e.g. BBCode) appended at the end of every description — leave empty to add nothing. A short "Uploaded with Nazgarr" line with the version always follows it.',
  'uploadSettings.signatureSaved': 'Signature saved.',
  'uploadSettings.saveSignatureButton': 'Save signature',
  'uploadSettings.imageHostsTitle': 'Image hosts',
  'uploadSettings.hostPlugin':
    'plugin',
  'uploadSettings.hostStatus.ready':
    'ready',
  'uploadSettings.hostStatus.missing':
    'API key missing',
  'uploadSettings.hostsRemoved':
    'These hosts are gone with the update: {hosts}. Enter the API key of at least one host below, or install a plugin for the one you used.',
  'uploadSettings.morePlugins':
    'Each host is a plugin: switch it off, or add more, in Settings › Plugins. A Chevereto host is a few lines.',
  'uploadSettings.imageHostsDescription':
    'The first host that is on and has its API key is tried first, then the next if it fails. Drag to change the order, tap a host for its key.',
  'uploadSettings.priorityOrderSaved': 'Priority order saved.',
  'uploadSettings.dragToReorder': 'Drag to reorder {label}',
  'uploadSettings.fileNamesTitle': 'File names in the torrent',
  'uploadSettings.fileNamesDescription':
    'When there is no torrent on a client with the same files (hardlink), the files of a new upload get a name built from this pattern, dot-separated like a release: no ":" or accents. The title is the one the upload’s trackers use, when they agree (the Italian one for ITT); otherwise the original. Each upload can still keep the original names.',
  'uploadSettings.fileNamesReset': 'Back to the default',
  'uploadSettings.releasesTitle': 'Your releases',
  'uploadSettings.releasesDescription':
    'For what you release yourself: put it in the watched folder of a disk (Settings › Storage) and the upload starts on its own, up to the decision. Once it seeds, it is moved to the releases folder: the watched folder is only a way in.',
  'uploadSettings.releaserLabel': 'Releaser name',
  'uploadSettings.releaserDescription': 'The group at the end of the names of the uploads from the watched folder, and of every upload whose name has no group (e.g. -NZG). Editable on each upload.',
  'uploadSettings.splitIncompleteLabel': 'Incomplete seasons as episodes',
  'uploadSettings.splitIncompleteDescription':
    'A season that reaches the watched folder without every episode (e.g. the first 2 of 8) becomes one upload per episode instead of an incomplete season pack. Once the last one seeds, its folder goes with whatever is left (nfo, sample).',
  'uploadSettings.autoMatchLabel': 'Automatic TMDB match',
  'uploadSettings.autoMatchDescription':
    'For every upload, by hand or from the watched folder: a match at least this sure (0-1) is confirmed on its own; below, or when two titles look alike, it waits for you. Change match takes it back. 0 turns it off. Default: 0.9.',
  'uploadSettings.autoRenameLabel': 'Rename files automatically',
  'uploadSettings.autoRenameHelp':
    'On: the names of the hardlinked torrent if there is one, otherwise this pattern for library files and watched-folder releases. Off: every upload starts with the original names; you can still pick another option on each upload.',
  'uploadSettings.singleFileLabel': 'Single file instead of a folder with one file',
  'uploadSettings.singleFileHelp':
    'When the only file going into the torrent sits in a folder, the torrent is just that file, with no folder. Samples and system files never go into the torrent, so they do not count; an nfo does, and the torrent stays a folder.',
  'uploadSettings.singleFileFolderLabel': 'Folder of the single file',
  'uploadSettings.singleFileFolder.keep': 'Keep the folder',
  'uploadSettings.singleFileFolder.remove': 'Remove the folder',
  'uploadSettings.singleFileFolderHelp.keep':
    'The file seeds inside its folder in the releases folder, and the client points there. A source already in the seeding folder seeds where it is.',
  'uploadSettings.singleFileFolderHelp.remove':
    'The file seeds directly in the releases folder, without its folder. A source already in the seeding folder seeds where it is, inside its folder.',
} as const
